/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MuseumImport } from './routes/museum'
import { Route as ConnectionsImport } from './routes/connections'
import { Route as CabinetImport } from './routes/cabinet'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MuseumRoute = MuseumImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsRoute = ConnectionsImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRoute,
} as any)

const CabinetRoute = CabinetImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetImport
      parentRoute: typeof rootRoute
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsImport
      parentRoute: typeof rootRoute
    }
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/connections': typeof ConnectionsRoute
  '/museum': typeof MuseumRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/connections': typeof ConnectionsRoute
  '/museum': typeof MuseumRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/connections': typeof ConnectionsRoute
  '/museum': typeof MuseumRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabinet' | '/connections' | '/museum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabinet' | '/connections' | '/museum'
  id: '__root__' | '/' | '/cabinet' | '/connections' | '/museum'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  ConnectionsRoute: typeof ConnectionsRoute
  MuseumRoute: typeof MuseumRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  ConnectionsRoute: ConnectionsRoute,
  MuseumRoute: MuseumRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cabinet",
        "/connections",
        "/museum"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cabinet": {
      "filePath": "cabinet.tsx"
    },
    "/connections": {
      "filePath": "connections.tsx"
    },
    "/museum": {
      "filePath": "museum.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
